apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendlens-event-drainer
  namespace: spendlens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spendlens-event-drainer
  template:
    metadata:
      labels:
        app: spendlens-event-drainer
    spec:
      serviceAccountName: spendlens-runtime
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: event-drainer
          image: spendlens/api:local
          imagePullPolicy: IfNotPresent
          command: ["node", "apps/api/dist/event-drainer.js"]
          envFrom:
            - configMapRef:
                name: spendlens-config
            - secretRef:
                name: spendlens-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
